import { COUNTRY_CODE_MAP } from './countryCodes.js';

// Explicit per-country overrides (one entry per country) with dummy values.
// Edit any country's values below. Example:
// COUNTRY_OVERRIDES["Germany"] = { additionalDuty: '1.50%', reciprocalTariff: '0.75%' };

export const COUNTRY_OVERRIDES = {
  "Afghanistan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Albania": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Algeria": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Andorra": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Angola": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Anguilla": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Antigua and Barbuda": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Argentina": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Armenia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Aruba": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Australia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Austria": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Azerbaijan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bahamas": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bahrain": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bangladesh": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Barbados": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Belarus": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Belgium": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Belize": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Benin": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bermuda": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bhutan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bolivia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bosnia and Herzegovina": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Botswana": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Brazil": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "British Indian Ocean Territory": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "British Virgin Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Brunei": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Bulgaria": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Burkina Faso": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Burma (Myanmar)": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Burundi": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cambodia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cameroon": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Canada": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cape Verde": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Caribbean Netherlands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cayman Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Central African Republic": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Chad": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Chile": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "China": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Christmas Island": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cocos (Keeling) Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Colombia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Comoros": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Congo, Democratic Republic": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Congo, Republic": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cook Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Costa Rica": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cote d'Ivoire": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Croatia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cuba": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Curaçao": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Cyprus": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Czech Republic": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Denmark": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Djibouti": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Dominica": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Dominican Republic": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Ecuador": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Egypt": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "El Salvador": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Equatorial Guinea": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Eritrea": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Estonia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Eswatini": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Ethiopia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Falkland Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Faroe Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Fiji": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Finland": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "France": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "French Guiana": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "French Polynesia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "French Southern Lands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Gabon": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Gambia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Gaza Strip": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Georgia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Germany": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Ghana": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Gibraltar": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Greece": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Greenland": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Grenada": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Guadeloupe": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Guam": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Guatemala": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Guinea": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Guinea-Bissau": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Guyana": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Haiti": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Heard Island": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Holy See": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Honduras": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Hong Kong": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Hungary": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Iceland": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "India": { additionalDuty: "10.00%", reciprocalTariff: "0%" },
  "Indonesia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Iran": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Iraq": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Ireland": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Israel": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Italy": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Jamaica": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Japan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Jordan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Kazakhstan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Kenya": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Kiribati": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Kosovo": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Kuwait": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Kyrgyzstan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Laos": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Latvia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Lebanon": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Lesotho": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Liberia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Libya": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Liechtenstein": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Lithuania": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Luxembourg": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Macau": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "North Macedonia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Madagascar": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Malawi": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Malaysia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Maldives": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Mali": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Malta": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Marshall Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Martinique": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Mauritania": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Mauritius": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Mayotte": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Mexico": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Micronesia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Moldova": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Monaco": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Mongolia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Montenegro": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Montserrat": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Morocco": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Mozambique": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Namibia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Nauru": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Nepal": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Netherlands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "New Caledonia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "New Zealand": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Nicaragua": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Niger": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Nigeria": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Niue": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Norfolk Island": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "North Korea": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Norway": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Oman": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Pakistan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Palau": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Panama": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Papua New Guinea": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Paraguay": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Peru": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Philippines": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Pitcairn Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Poland": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Portugal": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Puerto Rico": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Qatar": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Reunion": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Romania": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Russia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Rwanda": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Saint Barthelemy": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Saint Helena": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Saint Kitts and Nevis": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Saint Lucia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Saint Pierre and Miquelon": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Saint Vincent and the Grenadines": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Samoa": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "San Marino": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Sao Tome and Principe": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Saudi Arabia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Senegal": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Serbia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Seychelles": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Sierra Leone": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Singapore": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Sint Maarten": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Slovakia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Slovenia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Solomon Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Somalia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "South Africa": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "South Korea": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Sudan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "South Sudan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Spain": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Sri Lanka": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Suriname": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Svalbard": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Sweden": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Switzerland": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Syria": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Taiwan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Tajikistan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Tanzania": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Thailand": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Timor-Leste": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Togo": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Tokelau": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Tonga": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Trinidad and Tobago": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Tunisia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Turkiye": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Turkmenistan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Turks and Caicos Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Tuvalu": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Uganda": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Ukraine": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "United Arab Emirates": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "United Kingdom": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "United States": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "United States Minor Outlying Islands": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Uruguay": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Uzbekistan": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Vanuatu": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Venezuela": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Viet Nam": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Virgin Islands (US)": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Virgin Islands (British)": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Wallis and Futuna": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "West Bank": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Yemen": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Zambia": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" },
  "Zimbabwe": { additionalDuty: "1.00%", reciprocalTariff: "0.50%" }
};

export function getCountryOverrides(countryName) {
  if (!countryName) return null;
  return COUNTRY_OVERRIDES[countryName] || null;
}

export function setCountryOverride(countryName, override) {
  if (!countryName) return false;
  COUNTRY_OVERRIDES[countryName] = Object.assign({}, COUNTRY_OVERRIDES[countryName] || {}, override);
  return true;
}

export default {
  COUNTRY_OVERRIDES,
  getCountryOverrides,
  setCountryOverride
};
